= State and Collections

Many collections expect their values not to change, lest they stop working correctly.

== Hash Sets

A hash set is a data structure aiming to check for membership efficiently.
We first examine a naive implementation.

=== Lists

Let's look at how to check for membership using ordinary lists.
A list lets the user determine the order of the elements, so a list cannot make any assumption about where in the list elements reside.
When checking whether some value is contained within a list, we have no other choice than to go through the entire list:

[source,python]
----
def member(lst, elt):
    for x in lst:
        if x == elt:
            return True
    return False
----

This is acceptable for small lists, but as the lists grow longer, the time needed to find a particular increases linearly.
Even though linear isn't bad, but it can definitely be improved upon.

=== Internal Working of Hash Sets

What if instead of having one large list of elements, we have many very small ones?
Looking for an element in a small list is quite efficient.
But that raises the question: how do we know in which small list to look for the element?
If we have to look through every one, we might as well simply work with one large list.

We solve this problem by associating an arbitrary but deterministic number to each value we might want to store in a hash set.
This number is called the _hash code_.
We expound this:

* *Arbitrary*: the actual value does not matter, but the more random, the better.
* *Deterministic*: equal values should yield the same hash code every time.

We keep a large number of small lists and use this hash code to determine in which list an element belongs.
These small lists are generally called _buckets_.

[source,python]
----
class HashSet:
    def __init__(self):
        self.table = [ [] for _ in range(BUCKET_COUNT) ]  # <1>

    def add(self, elt):
        self.find_bucket(elt).append(elt)                 # <2>

    def find_bucket(self, elt):
        index = self.compute_bucket_index(elt)
        return self.table[index]

    def compute_bucket_index(self, elt):
        return hash(elt) % len(self.table)                # <3>

    def __contains__(self, elt):
        return elt in self.find_bucket(elt)               # <4>
----
<1> `table` keeps track of the buckets (small lists). We create `BUCKET_COUNT` such buckets.
<2> Adding an element `elt` involves first determining which bucket `elt` belongs in, then adding `elt` to this bucket.
<3> The bucket index is determined by using ``elt``'s hash code modulo `BUCKET_COUNT`.
<4> Looking if an element is a member of the set consists of looking up the right bucket and going through it. Since the bucket is a small list, this operation is efficient.

=== Mutable Elements

A problem arises when set elements are modified.
This causes their hash code to change.
This means that the element now resides in the wrong bucket.

[source,python]
----
elt = create()   # <1>
set.add(elt)     # <2>
elt.change()     # <3>
elt in set       # <4>
----
<1> `elt` is created. Let's assume `hash(elt) = 1`.
<2> `elt` is added the the set and is placed in the second bucket.
<3> ``elt``'s hash code changes to, say, `2`.
<4> `set` will wrongly look for `elt` in the third bucket instead of the second.

This means sets only work if you make sure the elements' hash code never changes once it's been added.
The most straightforward way to achieve this, is to make the elements immutable.

=== Python

Python tries to enforce this rule as best it can: sets and dictionaries (which also rely on hash codes) only accept elements (or keys, in the case of dictionaries) that are immutable.
For example,

* Since strings and numbers are immutable, they are valid elements.
* Lists are mutable and therefore cannot be added to sets or used as dictionary keys.
* Tuples are in essence immutable lists. These are okay to use.
* In a similar vein, sets in themselves are mutable, but here too Python offers an immutable alternative, namely `frozenset`.

== Other Examples

Data structures that organize elements according to their value will generally break if any elements they contain change.
For example, a binary search tree will break if its elements are modified.
